### ISSUE TITLE
Lead - Fix listing page filter

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#26]
![Image](https://github.com/user-attachments/assets/1597b4ac-7f63-493d-a239-3ce1e012fc52)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/44fdc931-e92f-4517-b240-6d2eee795c23)

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/a8363267-cae5-46c4-80ca-bd813d671b2f)

This issue was not fixed, please zoom in and zoom out for testing

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/ca3e7634-80c1-4b20-9270-c53da6c36806)

Filter menu pane hidden when not toggled

**Comment by Buzxxx** [comment]
We have patched right filter for now, we will work on it in future if needed
