### ISSUE TITLE
Re - Lead - Card not for mobile view

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#28]

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/c5af5253-67ed-478d-99fd-d7597932271b)

**Comment by Buzxxx** [comment]
created diff sstory to track api feature

**Comment by Buzxxx** [comment]
@subrathk please test this feature and share your feedback if this working fine

**Comment by subrathk** [comment]
yes sir its working

**Comment by subrathk** [comment]
sir in mobile card is not showing

**Comment by subrathk** [comment]
card for mobile view working fine


![Image](https://github.com/user-attachments/assets/8c75d710-bb88-48d8-a0f5-9099212bd623)

**Comment by subrathk** [comment]
1. menu option is opening on the left side the of the menu bar make it same as in the CRM website and after clicking in the menu button border  taping is not visible 
2. Lead heading should be in bold black colour
3. In menu button only two option are showing what about other options is it a bug or expected?
4. In card selecting button box  background should be in white colour 

![Image](https://github.com/user-attachments/assets/67ea422d-f7c0-4cc9-a611-807e32fbb13f)

**Comment by Buzxxx** [comment]
1. Use menu bar from schadcn
2. decide on theme for select

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/58bb86d1-673f-418d-a587-7cf5c6d53f38)

**Comment by subrathk** [comment]
lead-Card  is working fine in mobile view


![Image](https://github.com/user-attachments/assets/913c7f08-9ed2-4e9e-83ca-5c92a03018c6)

**Comment by Buzxxx** [comment]
Story is completed
