### ISSUE TITLE
Re - Lead - Multiple Reassign

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#29]

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/fedb6149-a6e7-4e32-9da8-0b631cd3ca53)

**Comment by subrathk** [comment]
Select user option bar size  has reduced and working fine ,
But after assigning the user , the confirm button is not loading ,please check and solve this issue , 



![Image](https://github.com/user-attachments/assets/6c67f4e9-d3a4-4dbf-930c-c70ce24d2214)

**Comment by grvx-github** [comment]
As per avinash, right now we are moving this to done.
