### ISSUE TITLE
Lead - Select all and counter on top

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#30]
![Image](https://github.com/user-attachments/assets/4d01e078-1605-46c1-9d00-7721da457014)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/b055fb23-c430-4b1f-a3f1-efcc35c7e41c)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/62804b7a-d10f-45d9-8d49-bb1124834ce0)

**Comment by grvx-github** [comment]
Same tab being used to display total number of leads & number of selected leads

**Comment by Buzxxx** [comment]
Select is working as expected

**Comment by Buzxxx** [comment]
Done and closed
