### ISSUE TITLE
Re-Re - Lead - Individual Lead page - Parent component

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#33]
![Image](https://github.com/user-attachments/assets/b78e1556-e695-43ed-874e-0d0c9b206da0)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/09bd0433-03c9-409f-b4fb-50e2c06c2f94)
![Image](https://github.com/user-attachments/assets/7194bbca-9743-4cec-9ec9-40025d230bee)
Added working navigation tabs

**Comment by subrathk** [comment]
![Image](https://github.com/user-attachments/assets/d2a5c1b9-c895-4c35-941c-1108424940dd)

**Comment by Buzxxx** [comment]
1. Name is small and not bold 
2. gap in status below name 
3. accordion buttons are diff from eheindustries and gap 
4. back icon is working fine
5. all icons are working fine
6. profile icon does not have border
7. div heights are too long compared to eheindustries 



![Image](https://github.com/user-attachments/assets/6a06a610-c0a1-4ff8-ac41-5c56108071c3)

**Comment by Buzxxx** [comment]
Buttons are fading when hovering over it 


![Image](https://github.com/user-attachments/assets/5e233b9d-d779-4bc4-8881-fee08ddcb333)

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/c2dc6a44-8a98-482f-bec2-915db8b3c4f9)



![Image](https://github.com/user-attachments/assets/0895e19b-dcd6-435d-9bff-098d0b7c9606)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/8abc8bb1-bdc9-498a-8eb2-9c123c27b41c)

Done

**Comment by subrathk** [comment]
parent component page is working fine 
but the submit in timeline is not able to submit or its a button problem please this once and make changes if its a problem
or it is expected to be like that?


![Image](https://github.com/user-attachments/assets/933510c7-740e-47a8-9cb0-575624c5bb74)

**Comment by subrathk** [comment]
1. green online signal button should be little close to cold button  and make it square green as it is in website
2. create a dropdown button in lead option to add new feature which has explained by avinash sir 
3. 

![Image](https://github.com/user-attachments/assets/84a36c09-25c2-47e2-b539-268ae06921d5)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/5be94530-3f96-48b5-a600-71c256f8c9b0)

Done

**Comment by subrathk** [comment]
Parent component page is working fine in both website and mobile view


![Image](https://github.com/user-attachments/assets/135d9b94-f9c6-4da5-9fc8-5ca4b7376b3b)




![Image](https://github.com/user-attachments/assets/fa436c10-d4e3-4b5c-921d-e849fd0ca673)

**Comment by Buzxxx** [comment]
Close
