### ISSUE TITLE
Re - Lead - Individiual Lead page - Timeline

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#34]

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/a2f00a93-17da-4dce-a9f2-71d048e92fbf)

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/b8337ff9-4831-4a6c-8d3a-7cf6bc91718b)

Create a UI for Timeline

**Comment by Buzxxx** [comment]
@grvx-github  Mobile view is not done, please look into it 


![Image](https://github.com/user-attachments/assets/af3ca2b8-85b4-4d6b-96e9-de2397427869)

**Comment by subrathk** [comment]
1.   After clicking timeline page in mobile view its turning white background in timeline box , after moving out cursor from the box it should  get  back in blue background as its in desktop view
2.  can u make it  blue dot sign white colour inside the dot  
3. 

![Image](https://github.com/user-attachments/assets/59d6c552-f1fa-401e-9f29-63ec09976600)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/f29d5ca6-f43c-40a3-8f6d-f4777878664d)

> After clicking timeline page in mobile view its turning white background in timeline box , after moving out cursor from the box it should get back in blue background as its in desktop view

that issue is related to the Button component and the global css variables since on hover it changes to var(--clr-secondary) 

Overall responsive

**Comment by grvx-github** [comment]
Resolved with other issues

**Comment by subrathk** [comment]
Individiual lead page -timeline is working fine in both website view and mobile view


![Image](https://github.com/user-attachments/assets/34dea31d-9dee-422a-9406-bb98e8fa3bfd)

**Comment by Buzxxx** [comment]
Close
