### ISSUE TITLE
Re-Lead - Individiual Lead page - Profile

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#35]

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/dbb88a58-5e04-45ec-b6b0-d47e34876f46)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/a3cc0635-7888-4856-951f-880566a04e0a)
![Image](https://github.com/user-attachments/assets/afbf4533-ed0e-4970-91e7-c65aa6556854)
![Image](https://github.com/user-attachments/assets/1b762730-4c8d-40b0-b96a-c5519293dd97)

**Comment by subrathk** [comment]
profile page is working fine


![Image](https://github.com/user-attachments/assets/9a57c59c-a217-4f80-9f89-ad4fd68a3158)

**Comment by subrathk** [comment]
profile page is also working fine in mobile view 


![Image](https://github.com/user-attachments/assets/09f861c9-b791-4a1d-b2c2-9e4632178f7d)

**Comment by Buzxxx** [comment]
Done and closed

**Comment by subrathk** [comment]
1. In profile page the product type is showing two times ,please solve this issue.



![Image](https://github.com/user-attachments/assets/1138e1db-af4b-426c-b01b-7493bfba7730)

**Comment by subrathk** [comment]
Individual page -profile is working fine in both website and mobile view


![Image](https://github.com/user-attachments/assets/a62a5ae2-76ca-4656-b952-7628af739cf4)




![Image](https://github.com/user-attachments/assets/3246f420-3d91-43d2-9808-fd4a7f2c9693)

**Comment by Buzxxx** [comment]
Closed
