### ISSUE TITLE
Re - Lead - Individiual Lead page - Call back

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#36]

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/514af96d-2ab2-483a-8f38-cb98a28041d4)

**Comment by subrathk** [comment]
1. Do not give more spaces in between the profile and and timeline and so on 
2. In last set a follow up button after clicking it ,the inside text in not visible bcoz of white background can u change it to blue as it in the upper page or any better options?
3.  we dont required spaces in  both left and right sides pls change it 
4. 

![Image](https://github.com/user-attachments/assets/64d999ec-9993-4b11-b464-e8e11005473c)

**Comment by subrathk** [comment]
1.  In mobile view  after clicking on option in timeline , profile , call back  or meeting option the clicked box in not highlighting in blue bolder its coming in white background in mobile view   , can u do it  as it is which in showing in  desktop view 
2. 

![Image](https://github.com/user-attachments/assets/ddd2563f-a85f-4b2e-95e9-124d5c3b923a)

**Comment by Buzxxx** [comment]
Default date and time

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/f28624e2-5650-4dfa-9406-f5848f9d3935)



Default date & time set to current date & time

**Comment by subrathk** [comment]
lead-Individual lead page- call back is working fine in both website and mobile view


![Image](https://github.com/user-attachments/assets/5022f5aa-0d6d-4f69-bb4c-925dd613af51)




![Image](https://github.com/user-attachments/assets/f688f78a-11fe-4290-a80c-6c7e6563e9e9)

**Comment by Buzxxx** [comment]
Close
