### ISSUE TITLE
Re - Lead - fetch lead from Api for lead listing page

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#44]

**Comment by Buzxxx** [comment]
https://www.eheindustries.com/lead/api/leads?filter_by=&page=1000

https://www.eheindustries.com/lead/api/leads?filter_by=id:48;status:new;source:99acres&sort_by=recieved_date&per_page=1&page=2

https://www.eheindustries.com/lead/api/leads?filter_by=id:[49,55]

**Comment by subrathk** [comment]
Fetch lead from Api for lead listing page is working fine in both desktop and mobile view.



![Image](https://github.com/user-attachments/assets/fdf729c7-e8db-4849-a9d0-b57cf836bfec)




![Image](https://github.com/user-attachments/assets/39407a45-fd9e-4322-85f7-570f4419a423)

**Comment by subrathk** [comment]
1. https://www.eheindustries.com/lead/api/leads?filter_by=&page=1000  , this URL is working fine .

2.  https://www.eheindustries.com/lead/api/leads?filter_by=id:%5B49,55%5D , this URL is also working fine .

3.  https://www.eheindustries.com/lead/api/leads?filter_by=id:48;status:new;source:99acres&sort_by=recieved_date&per_page=1&page=2 ,  in this URL status:new; is not working fine. please check this issue and make changes .
