### ISSUE TITLE
Lead - Filtering system

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#47]
![Image](https://github.com/user-attachments/assets/e3eb50c4-dc86-4e85-b953-5e7b658e9c70)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/f89c4458-53f9-4be6-8cc2-8bcf9a9ff4af)

**Comment by Buzxxx** [comment]
After https://github.com/users/Buzxxx/projects/1/views/1?pane=issue&itemId=74676188, we will work on it 
http://127.0.0.1:8000/lead/api/leads?filter_by=id:48;status:new;source:99acres&sort_by=recieved_date&per_page=1&page=2

**Comment by Buzxxx** [comment]
![Image](https://github.com/user-attachments/assets/287a4ca7-df40-485e-b57e-f58881291c99)

Lead Icon updates

**Comment by Buzxxx** [comment]
on click status dropdown, filter is moving down 

![Image](https://github.com/user-attachments/assets/a0c979d7-3cc6-4229-b9e1-ecb6e5fa2da0)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/ec7b5bb2-139c-4ad0-80a8-a67df946eebf)

fixed

**Comment by subrathk** [comment]
The filter icon colour has changed  to black blue , it should be in grey colour ,
In status box it is showing only 1 option to select, please check this issue and make changes .



![Image](https://github.com/user-attachments/assets/b583bc33-8274-40a0-908a-3488a5c1739d)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/66060e59-bfe1-4b40-87ae-b70988100f3f)

ui changes

**Comment by subrathk** [comment]
1. In filtering system the status dropdown is showing only 1 option .
2. The scrolling option should not be visible in desktop view pls check this issue and make changes .
3. while selecting custom date the in from and to the page is getting down , please check this and make changes . 



![Image](https://github.com/user-attachments/assets/c66b1145-cd85-495e-bc5f-c6660c14a478)


1. In mobile view filter option is not visible , please check and solve this issue .
2. we need scrolling button in mobile view for filter dropdown .



![Image](https://github.com/user-attachments/assets/63df13dc-f8b3-402a-9137-371649a9c343)

**Comment by subrathk** [comment]
Lead Filtering system is working fine in desktop and mobile view , but the filter option is not visible in mobile view .



![Image](https://github.com/user-attachments/assets/3fe8d73d-f0c1-4e4b-9d25-13c34523fe13)




![Image](https://github.com/user-attachments/assets/451daa0d-7f36-4da6-924d-edeab885bb27)

**Comment by subrathk** [comment]
Lead filtering system is working fine in both desktop and mobile view.
![Image](https://github.com/user-attachments/assets/f9f88e46-d5d7-44b7-90a0-c75cae61636d)

![Image](https://github.com/user-attachments/assets/a0b25ac7-4b09-4703-ba15-86a4b7f7f2a7)
