### ISSUE TITLE
Collect all icons in one folder

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#48]
Go to below pages and collect SVGs
1. dashboard
2. Lead
3. workforce
4. workplace
5. settings
6. login
7. signup

**Comment by Buzxxx** [comment]
@subrathk please test,  compare index.ts file with all icons on eheindia domain

**Comment by subrathk** [comment]
Icons list  to make changes 
List,
  Filter,
  Notebook,
  ListChecks,
  ShoppingCart,
  LogOut,
  Contact,
  Pencil,
  CircleUserRound,

**Comment by subrathk** [comment]
new changes in icon folder have added and working fine

**Comment by Buzxxx** [comment]
Close
