### ISSUE TITLE
Lead - lead listing UI enhanacement

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#55]
![Image](https://github.com/user-attachments/assets/7c251fa5-3309-40b2-88a6-9ad35539805f)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/2cc79e81-c5b8-417c-b1ab-7943a487edb3) <=746px
![Image](https://github.com/user-attachments/assets/ed327645-edd7-4422-ba77-7b155b309ca5) >=747px

**Comment by subrathk** [comment]
lead listing UI enhancement
1. after clicking hamburger button,  the whatsapp button and call button is  getting out of the card box allignment ,make this changes



![Image](https://github.com/user-attachments/assets/e2fc9c46-c6cc-49e1-8c58-a4306357f687)



In mobile view its working fine


![Image](https://github.com/user-attachments/assets/be426ea4-5016-4a8a-90fb-0e41e7cbe10c)

**Comment by subrathk** [comment]
whtasapp logo is showing  two times  make the changes

![Image](https://github.com/user-attachments/assets/d01befa3-9b85-4f66-aa6d-1b77cf0c0b34)

**Comment by subrathk** [comment]
lead listing UI enhancement working fine


![Image](https://github.com/user-attachments/assets/24fe9d0e-96ce-40e3-b5ea-6196d91e8c1a)


In mobile view its working fine


![Image](https://github.com/user-attachments/assets/386e28e3-1c5b-4c48-a0f9-a2483d7f6a43)

**Comment by Buzxxx** [comment]
Done
