### ISSUE TITLE
Re-Re-Dashboard - By default left navigation should be closed in Mobile view

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#58]
![Image](https://github.com/user-attachments/assets/01df147d-731c-4737-8602-dad17ed69980)

**Comment by subrathk** [comment]
left navigation bar is not closing by default in mobile view, still having the same issue ,please check it again.


![Image](https://github.com/user-attachments/assets/ff4282a6-d591-4d22-9795-e4d98f9bb457)

**Comment by subrathk** [comment]
1. The navigation bar is not closed properly by default in mobile view ,please check this issue.


![Image](https://github.com/user-attachments/assets/b4a3b1d5-c675-4dfe-beb9-8edd404de676)


2. After opening navigation bar ,if we click anywhere out of the navigation bar, it is not closing by default ,please check this issue .


![Image](https://github.com/user-attachments/assets/51d4e8fe-c9f2-4001-8c66-562cdb11ce7f)

**Comment by subrathk** [comment]
By default navigation bar is getting closed , if we are clicking  out of the navigation bar it is getting closed , its working fine in mobile . no issues .

**Comment by Buzxxx** [comment]
Done
