### ISSUE TITLE
Re - Lead - Create single lead

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#65]
Endpoint URL - https://www.eheindustries.com/lead/api/createlead
Sample JSON -

{
"name" : "Avinash",
"email" : "avi@gmail.com",
"contact" :  "919163833719",
"lead_type" : "Domestic",
"query" : "I am Interested",
"interested_in" : "Rent in DLF New Town Heights 1, Sector-90, Gurgaon", 
"assigned_to" : "Avinash.jha",
"product_code"  : "DFT145",
"product_type" : "Commercial",
"source" :"4",
"status" : 1,
"priority" : "cold"
}
success response with status 200 -
{
"message": "Lead created successfully"
}

**Comment by grvx-github** [comment]
// "name" : "Avinash", String
// "email" : "avi@gmail.com", Email
// "contact" : "919163833719", Phone WIth country code
// "lead_type" : "Domestic", String
// "query" : "I am Interested",String
// "interested_in" : "Rent in DLF New Town Heights 1, Sector-90, Gurgaon", String -- Textbox
// "assigned_to" : "Avinash.jha", Dropdown
// "product_code" : "DFT145", Text
// "product_type" : "Commercial", Text
// "source" :"4", Dynamic userId - NON SELECTaBLE
// "status" : 1, DEFAULT
// "priority" : "cold" Dropdown

**Comment by Buzxxx** [comment]
name = Text field
    email = Email field
    contact =  Number field with country code added
    lead_type = Text field
    query = Text field
    interested_in = Text field
    assigned_to = Dropdown fetched from API - username text
    product_code  = Text field
    product_type = Text field Optional
    source = Set dynamic as UserId
    status = Set default as 1
    priority = Drop down [cold, warm and hot]

**Comment by subrathk** [comment]
Create lead page is working fine 


![Image](https://github.com/user-attachments/assets/8029d398-1bcd-422f-add6-ff7ab1e777f3)

**Comment by subrathk** [comment]
In all leads ,  we are having an issue of checkbox is not able select , after clicking on it ,its getting popup and disabled again, please check this and make changes .



![Image](https://github.com/user-attachments/assets/0a970b78-56a2-4495-ba52-826b131920b1)

**Comment by subrathk** [comment]
1. The number box is not having curved finishing as other input boxes ,
2.  Interested in box should be in smaller in size as other boxes , bcoz its not looking good in different alignment with other boxes please check and change this issue 
3. After clicking create button, it is not creating the new lead and its getting refreshing the details filled in create new lead , please check this and solve this issue .



![Image](https://github.com/user-attachments/assets/d6f4491e-6f27-4134-8471-57a9c8fc41ae)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/309448e8-f8e5-44a4-9cd2-0a9c3d5d156c)

**Comment by subrathk** [comment]
Create lead is working fine in desktop and mobile view .



![Image](https://github.com/user-attachments/assets/a2ad0e9e-c8da-40e0-9f84-50ad2c104f30)





![Image](https://github.com/user-attachments/assets/a0f148a4-e1f3-442f-8c36-961a53de57bc)
