### ISSUE TITLE
Re - Lead - Create pagination buttons in lead page

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#67]
![Image](https://github.com/user-attachments/assets/469b71b0-99b5-46fa-98b0-e7fff3d06021)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/57a12195-e0a1-4d79-9821-b571c44a2969)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/eefac8a1-5504-48fe-bb45-6a913e1b2a60)

**Comment by subrathk** [comment]
Create pagination buttons in lead page is working fine.



![Image](https://github.com/user-attachments/assets/60a904b8-9926-43e9-9831-57cd5afc582f)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/a272497a-6a09-449a-84e8-39b6bb986cef)



![Image](https://github.com/user-attachments/assets/21541433-183a-402e-b1d2-e82345ee8115)

**Comment by subrathk** [comment]
Pagination buttons are working fine in desktop view.


![Image](https://github.com/user-attachments/assets/cebaf8a5-32e7-4dca-b913-4ac21aca3cc3)

pagination button is not visible in mobile view  is this expected ? or this is a issue u need to change later?



![Image](https://github.com/user-attachments/assets/fdac6e1e-feb5-4322-982b-25273aee6a76)

**Comment by subrathk** [comment]
1. The per page is triggering so check this issue and fix it.
2. In the dropdown UI, we will have to reduce the per page options to : 10, 20, 50, 100, 200.
3. We have to show the total no of items fetched.


![Image](https://github.com/user-attachments/assets/19def6ea-631a-4de0-a37a-bc9ddbc4036c)

**Comment by subrathk** [comment]
In pagination button , page and  per page dropdown is working fine .



![Image](https://github.com/user-attachments/assets/85528821-c4c8-46bf-aeb7-9a1e4cc0f05a)

**Comment by Buzxxx** [comment]
Done
