### ISSUE TITLE
Lead Page - console form fields and validate

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#72]
![Image](https://github.com/user-attachments/assets/ca7399d1-3b35-4be9-9f07-86fb808652e5)

**Comment by subrathk** [comment]
console form fields and validate is working fine , But the 'set a follow up' button is not showing as **done** after creating it , please check this issue and make changes .


![Image](https://github.com/user-attachments/assets/93f4e7b5-4d08-41de-addb-798b85ec07ee)

**Comment by subrathk** [comment]
console form fields and validate is working fine in both desktop and mobile view .



![Image](https://github.com/user-attachments/assets/e8026489-ac29-447e-add8-18d92554731a)




![Image](https://github.com/user-attachments/assets/26c7c4ec-094f-46a6-8e23-243af117c69f)
