### ISSUE TITLE
Workforce - create tables for subuser/staff/emplyees

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#80]
![Image](https://github.com/user-attachments/assets/996b0b79-0f45-436c-a26f-0436a08a7f5a)

1. A table with 6 cols
2. In mobile view remove email, manager and phone number
3. Edit Icon
4. disable Icon
5. Add alias username button

**Comment by Buzxxx** [comment]
Enhancement/new feature - Create two sections for Active and Inactive users

**Comment by subrathk** [comment]
workforce - create table is working fine in desktop view , 



![Image](https://github.com/user-attachments/assets/87eef445-8ec1-48ab-9c18-fe0c509a3827)

In mobile view , workforce -create table is working fine ,


![Image](https://github.com/user-attachments/assets/431b88ef-3e1f-4040-84c0-734cc16d016a)

In mobile view , after clicking on workforce, all user  and  create user , the navigation bar is not closing by default .



![Image](https://github.com/user-attachments/assets/20b1c5ae-d1f0-46fd-afcf-b0a2328ae63f)

**Comment by subrathk** [comment]
Create table for user is working fine  in Desktop and mobile view.



![Image](https://github.com/user-attachments/assets/56ed5183-d89d-45c5-a572-029255cfd2ba)



![Image](https://github.com/user-attachments/assets/24f9fce3-4061-49cc-bad0-acb159ccb1bb)
