### ISSUE TITLE
Workforce - Onboard new subuser/create new subuser

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#81]
Make a form with the following fields - 
1. first name* - text field
2. second name - text field
3. last name* - text field
4. username* - text field 
5. Email* - email field
6. phone number* - number field
7. supervisor - dropdown 
8. Submit button

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/20f4252a-3e61-4fee-86de-90134ff915df)

**Comment by subrathk** [comment]
workforce-onboard for new sub user is working fine in desktop view .


![Image](https://github.com/user-attachments/assets/10eb810d-5c93-476f-9a42-01b6d0ec0f05)



workforce- onboard for new sub user is working fine is mobile view , 
1. Remove this empty spaces for mobile view ,please check and make changes .
2. after clicking on workforce create user , the navigation bar is not closing by default in mobile view , please check and make changes.


![Image](https://github.com/user-attachments/assets/9b48b9fd-e605-4609-93e6-c609cda23e17)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/821a3c94-25de-4d3d-bf99-12be6e6bccb3)

**Comment by subrathk** [comment]
Create new lead is working fine in desktop and mobile view , but small issues are there, 



![Image](https://github.com/user-attachments/assets/c8ba0108-e61e-4aa7-9a00-85286d8cca06)








1.In mobile view there is a small changes in corner line ,white line is getting visible , please check it and remove it.
2.In mobile view after clicking on create lead the navigation button is not getting closed by default.


![Image](https://github.com/user-attachments/assets/90f95d0f-0a58-45a2-b220-e9336a10b60c)



![Image](https://github.com/user-attachments/assets/d0df2950-c46d-44c6-bab6-156ea54505c6)

**Comment by grvx-github** [comment]
We already have separate story for dashboard navigation menu. Moving this story to done.
