### ISSUE TITLE
Workforce - Edit subuser details

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#82]
Create a new page/URL for this (we will use it as a model in the future) - 
some of the fields required in Edit page are - 
1.  First name
2. middle name
3. last name
4. mobile
5. supervisor user

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/a63ab7b2-393a-4e1b-a531-35537dba4acd)

**Comment by subrathk** [comment]
workforce-edit sub user details is working fine , in desktop view.

remove the  'required' word  for both desktop and mobile view , if it is necessary to add it , add some were in down , please check this make changes . 


![Image](https://github.com/user-attachments/assets/24c2a371-3bf8-4797-9c13-6dcf9b4923ed)

workforce-edit sub user is working fine in mobile view , 

Remove the 'required'  word and the spaces left , please check and make changes .


![Image](https://github.com/user-attachments/assets/1dbb8f57-d72f-43d7-8203-8eaa8f27da13)

**Comment by subrathk** [comment]
Edit sub user  is working fine in desktop and mobile view , 


![Image](https://github.com/user-attachments/assets/504cabc1-edc4-44b8-91dc-098f92bb5520)

In mobile view , small issue is there ,
1.Remove the spaces in between workforce and name .



![Image](https://github.com/user-attachments/assets/0755ac96-02c8-4e05-b752-0fda7b027b15)

**Comment by subrathk** [comment]
Workforce - Edit user details is working fine in both desktop and mobile view.
![Image](https://github.com/user-attachments/assets/0d81a9bd-47ee-4d77-808e-83c05c233de8)
