### ISSUE TITLE
Workforce - Create a Modal for Active/Inactive user confirmation

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#83]
![Image](https://github.com/user-attachments/assets/d8668f17-3026-499b-b1ae-e9c15f24313c)

**Comment by subrathk** [comment]
create model for active and inactive is working fine in both desktop and mobile view 



![Image](https://github.com/user-attachments/assets/ac77ad2c-9f24-4a35-a625-42339cfe9600)


 In mobile 



![Image](https://github.com/user-attachments/assets/62459f70-c9ab-4798-b06b-feccbafffb76)




![Image](https://github.com/user-attachments/assets/a99155b3-6cf6-4bf4-a86c-642cf63729f1)
