### ISSUE TITLE
Workforce - Create a new page/URL for create aliasname for users

### ISSUE THREAD

**Issue by Buzxxx** [Buzxxx/ehe_next#84]
![Image](https://github.com/user-attachments/assets/3cf4cffd-3679-46dc-acb9-7e792fd3e51f)

**Comment by grvx-github** [comment]
![Image](https://github.com/user-attachments/assets/85d51f08-e249-4841-adad-255fed87a1ec)

**Comment by subrathk** [comment]
create alias user name is not working in both desktop and mobile view , after clicking on add alias page is not opening , please check this issue and make changes .



![Image](https://github.com/user-attachments/assets/003afef0-e3e0-4647-8985-538f47fe2a65)




![Image](https://github.com/user-attachments/assets/f78b5ccf-faca-4af6-ae6e-57fff682c4fe)

**Comment by grvx-github** [comment]
Fixed.

Create alias now redirecting to edit aliases page

**Comment by subrathk** [comment]
New alias user name page is working fine , but the new added name changes is not showing in console log , please check this issue and make changes. 


![Image](https://github.com/user-attachments/assets/632352dd-0a4d-45b6-b538-8744252bd618)

**Comment by subrathk** [comment]
Workforce- create a new page for alias name user is working fine in both desktop and mobile view.

![Image](https://github.com/user-attachments/assets/45f9cdea-bb15-441f-b3c8-667991f62f00)

![Image](https://github.com/user-attachments/assets/6c926ef1-0a2c-4916-9b51-c08a14c1a199)
